// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzkd3FspsDLDZHqRsrG-u6k4ZuE9DMnfU',
    appId: '1:353782118586:web:46b07a6f9f8b12a48a2a83',
    messagingSenderId: '353782118586',
    projectId: 'courseproject-7c06c',
    authDomain: 'courseproject-7c06c.firebaseapp.com',
    databaseURL: 'https://courseproject-7c06c-default-rtdb.firebaseio.com',
    storageBucket: 'courseproject-7c06c.appspot.com',
    measurementId: 'G-5QB1575E8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg8kesTqo4tBKKeunMnYPhUt8UYcOyPpo',
    appId: '1:353782118586:android:d45ce0ead290983b8a2a83',
    messagingSenderId: '353782118586',
    projectId: 'courseproject-7c06c',
    databaseURL: 'https://courseproject-7c06c-default-rtdb.firebaseio.com',
    storageBucket: 'courseproject-7c06c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb125DrrxWgStm-cODCN6Bb5zU0sr8R4w',
    appId: '1:353782118586:ios:140af82f9fc3c3648a2a83',
    messagingSenderId: '353782118586',
    projectId: 'courseproject-7c06c',
    databaseURL: 'https://courseproject-7c06c-default-rtdb.firebaseio.com',
    storageBucket: 'courseproject-7c06c.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb125DrrxWgStm-cODCN6Bb5zU0sr8R4w',
    appId: '1:353782118586:ios:140af82f9fc3c3648a2a83',
    messagingSenderId: '353782118586',
    projectId: 'courseproject-7c06c',
    databaseURL: 'https://courseproject-7c06c-default-rtdb.firebaseio.com',
    storageBucket: 'courseproject-7c06c.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzkd3FspsDLDZHqRsrG-u6k4ZuE9DMnfU',
    appId: '1:353782118586:web:723c63b7a6cf78d18a2a83',
    messagingSenderId: '353782118586',
    projectId: 'courseproject-7c06c',
    authDomain: 'courseproject-7c06c.firebaseapp.com',
    databaseURL: 'https://courseproject-7c06c-default-rtdb.firebaseio.com',
    storageBucket: 'courseproject-7c06c.appspot.com',
    measurementId: 'G-RR3JP6DHTB',
  );
}
